# Generated by Django 3.2.6 on 2021-09-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0005_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('cliente', models.ManyToManyField(to='estudiante.Cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
