# Generated by Django 3.2.6 on 2021-09-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0007_docente_estudiante_grados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grados',
            name='grado',
            field=models.CharField(max_length=50),
        ),
    ]
